export interface Test {
  id: string;
  name: string;
  lastRun: string;
  status: 'passed' | 'failed' | 'pending';
  duration?: number;
}

const testCategories = {
  'UI TESTS': [
    'Login Form Validation',
    'Navigation Menu Rendering',
    'Dashboard Layout Responsiveness',
    'Modal Dialog Interactions',
    'Button Hover States',
    'Form Input Focus States',
    'Dropdown Menu Behavior',
    'Tooltip Positioning',
    'Card Component Rendering',
    'Table Pagination',
    'Search Bar Functionality',
    'Filter Panel Interactions',
    'Sidebar Navigation',
    'Header Component',
    'Footer Links',
    'Profile Avatar Display',
    'Notification Badge',
    'Loading Spinner Animation',
    'Error Message Display',
    'Success Toast Notification',
    'Tab Navigation',
    'Accordion Expand/Collapse',
    'Image Gallery Grid',
    'Video Player Controls',
    'Audio Playback UI',
    'Chart Legend Rendering',
    'Graph Tooltip Display',
    'Calendar Widget',
    'Date Picker Interactions',
    'Time Selector',
    'Color Picker Component',
    'File Upload Button',
    'Progress Bar Animation',
    'Breadcrumb Navigation',
    'Pagination Controls',
    'Skeleton Loading State',
    'Empty State Display',
    'Error Boundary Rendering',
    'Theme Switcher',
    'Language Selector',
    'Settings Panel',
    'User Menu Dropdown',
    'Search Results Layout',
    'Product Card Grid',
    'Shopping Cart Icon',
    'Checkout Form',
    'Payment Method Selector',
    'Address Form Validation',
    'Order Summary Display',
    'Invoice Template',
  ],
  'INTEGRATION TESTS': [
    'API Authentication Flow',
    'User Registration Process',
    'Login with OAuth',
    'Password Reset Flow',
    'Email Verification',
    'Two-Factor Authentication',
    'Session Management',
    'Token Refresh Logic',
    'Logout Functionality',
    'User Profile Update',
    'Avatar Upload',
    'Settings Persistence',
    'Notification Preferences',
    'Data Synchronization',
    'Real-time Updates',
    'WebSocket Connection',
    'Push Notifications',
    'File Upload to Cloud',
    'Image Processing Pipeline',
    'Video Transcoding',
    'PDF Generation',
    'Email Sending',
    'SMS Notifications',
    'Payment Gateway Integration',
    'Stripe Checkout Flow',
    'PayPal Payment Processing',
    'Subscription Management',
    'Invoice Generation',
    'Refund Processing',
    'Webhook Handling',
    'Third-party API Calls',
    'Google Maps Integration',
    'Analytics Tracking',
    'Error Logging Service',
    'Search Engine Integration',
    'Social Media Sharing',
    'Export to CSV',
    'Import from Excel',
    'Backup Creation',
    'Data Restore',
    'Database Migration',
    'Cache Invalidation',
    'CDN Purge',
    'Rate Limiting',
    'API Versioning',
    'CORS Configuration',
    'Security Headers',
    'Content Security Policy',
    'XSS Prevention',
    'CSRF Protection',
  ],
  'UNIT TESTS': [
    'String Utility Functions',
    'Date Formatting Helpers',
    'Number Validation',
    'Email Validator',
    'URL Parser',
    'JSON Serialization',
    'Array Manipulation',
    'Object Deep Clone',
    'Debounce Function',
    'Throttle Function',
    'Local Storage Helper',
    'Session Storage Helper',
    'Cookie Management',
    'Query String Parser',
    'Path Normalization',
    'File Size Formatter',
    'Currency Formatter',
    'Percentage Calculator',
    'Math Utilities',
    'Random String Generator',
    'UUID Generator',
    'Hash Function',
    'Encryption Utility',
    'Decryption Utility',
    'Base64 Encoding',
    'Base64 Decoding',
    'HTML Sanitizer',
    'Markdown Parser',
    'Template Engine',
    'Regular Expression Utils',
    'Validation Schema',
    'Type Guards',
    'Error Handler',
    'Logger Utility',
    'Event Emitter',
    'Observer Pattern',
    'Singleton Pattern',
    'Factory Pattern',
    'Builder Pattern',
    'Adapter Pattern',
    'Decorator Pattern',
    'Proxy Pattern',
    'State Machine',
    'Command Pattern',
    'Strategy Pattern',
    'Chain of Responsibility',
    'Mediator Pattern',
    'Memento Pattern',
    'Visitor Pattern',
    'Composite Pattern',
    'Flyweight Pattern',
    'Bridge Pattern',
    'Abstract Factory',
    'Prototype Pattern',
    'Iterator Pattern',
    'Interpreter Pattern',
    'Null Object Pattern',
    'Object Pool',
    'Service Locator',
    'Repository Pattern',
    'Unit of Work',
    'Data Mapper',
    'Active Record',
    'Table Gateway',
    'Row Gateway',
    'Identity Map',
    'Lazy Load',
    'Value Object',
    'Money Object',
    'Special Case',
    'Plugin Architecture',
    'Dependency Injection',
    'Service Container',
    'Event Sourcing',
    'CQRS Pattern',
    'Saga Pattern',
    'Circuit Breaker',
    'Retry Logic',
    'Bulkhead Pattern',
    'Cache Aside',
    'Read Through Cache',
    'Write Through Cache',
    'Write Behind Cache',
    'Refresh Ahead',
    'Sidecar Pattern',
    'Ambassador Pattern',
    'Anti-Corruption Layer',
    'Strangler Fig',
    'Backends for Frontends',
    'API Gateway',
    'Aggregator Pattern',
    'Proxy Pattern API',
    'Chained Pattern',
    'Branch Pattern',
    'Scatter Gather',
    'Pipes and Filters',
    'Priority Queue',
    'Load Leveling',
    'Competing Consumers',
    'Publisher Subscriber',
    'Request Reply',
    'Choreography',
    'Orchestration',
  ],
  'E2E TESTS': [
    'Complete User Journey',
    'New User Onboarding',
    'Purchase Flow End-to-End',
    'Account Creation to Checkout',
    'Search to Product View',
    'Add to Cart Flow',
    'Guest Checkout Process',
    'Registered User Checkout',
    'Apply Coupon Code',
    'Multiple Items Purchase',
    'Wishlist Management',
    'Product Review Submission',
    'Contact Form Submission',
    'Newsletter Signup',
    'Account Settings Update',
    'Password Change Flow',
    'Email Preference Update',
    'Address Book Management',
    'Payment Method Addition',
    'Order History View',
    'Order Tracking',
    'Return Request',
    'Support Ticket Creation',
    'Live Chat Interaction',
    'FAQ Search',
    'Product Comparison',
    'Filter and Sort Products',
    'Mobile Responsive Flow',
    'Cross-browser Testing',
    'Accessibility Compliance',
    'Performance Metrics',
    'SEO Validation',
    'Social Sharing',
    'Print Functionality',
    'Download Receipt',
    'Export Data',
    'Import Data',
    'Bulk Operations',
    'Admin Dashboard Access',
    'User Management',
    'Content Management',
    'Analytics Dashboard',
    'Report Generation',
    'Data Export',
    'System Configuration',
    'Backup and Restore',
    'Multi-language Support',
    'Multi-currency Support',
    'Geolocation Features',
    'Notification System',
  ],
  'PERFORMANCE TESTS': [
    'Page Load Time',
    'Time to First Byte',
    'First Contentful Paint',
    'Largest Contentful Paint',
    'Time to Interactive',
    'Total Blocking Time',
    'Cumulative Layout Shift',
    'API Response Time',
    'Database Query Performance',
    'Cache Hit Rate',
    'Memory Usage',
    'CPU Utilization',
    'Network Bandwidth',
    'Concurrent Users Load',
    'Stress Test 1000 Users',
    'Stress Test 5000 Users',
    'Stress Test 10000 Users',
    'Spike Load Test',
    'Endurance Test 24h',
    'Endurance Test 72h',
    'Scalability Test',
    'Volume Test Large Dataset',
    'Image Optimization',
    'Video Streaming Performance',
    'Bundle Size Analysis',
    'Code Splitting Efficiency',
    'Lazy Loading Performance',
    'Service Worker Cache',
    'IndexedDB Performance',
    'WebSocket Throughput',
    'GraphQL Query Performance',
    'REST API Latency',
    'Database Connection Pool',
    'Redis Cache Performance',
    'CDN Performance',
    'DNS Resolution Time',
    'SSL Handshake Time',
    'Compression Ratio',
    'Minification Impact',
    'Tree Shaking Results',
    'Critical CSS Extraction',
    'Font Loading Strategy',
    'Third-party Script Impact',
    'Analytics Loading Time',
    'Ad Network Performance',
    'A/B Test Framework',
    'Feature Flag Performance',
    'Error Tracking Overhead',
    'Logging Performance Impact',
    'Monitoring System Load',
  ],
  'SECURITY TESTS': [
    'SQL Injection Prevention',
    'XSS Attack Prevention',
    'CSRF Token Validation',
    'Authentication Bypass Test',
    'Authorization Check',
    'Session Hijacking Prevention',
    'Clickjacking Protection',
    'SSL/TLS Configuration',
    'HTTPS Enforcement',
    'Secure Cookie Flags',
    'Password Strength Policy',
    'Brute Force Protection',
    'Rate Limiting',
    'API Key Validation',
    'OAuth Token Security',
    'JWT Signature Verification',
    'Input Sanitization',
    'Output Encoding',
    'File Upload Validation',
    'Path Traversal Prevention',
    'XML External Entity Prevention',
    'LDAP Injection Prevention',
    'Command Injection Prevention',
    'Code Injection Prevention',
    'Server-Side Request Forgery',
    'Open Redirect Validation',
    'Insecure Deserialization',
    'Sensitive Data Exposure',
    'Missing Function Level Access',
    'Security Misconfiguration',
    'Using Components with Known Vulnerabilities',
    'Insufficient Logging',
    'Cryptographic Failures',
    'Broken Access Control',
    'Identification and Auth Failures',
    'Software and Data Integrity',
    'Security Logging',
    'Server Security Hardening',
    'Database Security',
    'API Security',
    'Mobile Security',
    'Cloud Security Configuration',
    'Container Security',
    'Secrets Management',
    'Encryption at Rest',
    'Encryption in Transit',
    'Key Management',
    'Certificate Validation',
    'CORS Policy',
    'Content Security Policy',
  ],
  'ACCESSIBILITY TESTS': [
    'Keyboard Navigation',
    'Screen Reader Compatibility',
    'Focus Management',
    'ARIA Labels',
    'ARIA Roles',
    'ARIA States',
    'Semantic HTML',
    'Heading Hierarchy',
    'Alt Text for Images',
    'Form Label Association',
    'Error Message Accessibility',
    'Color Contrast Ratio',
    'Text Resize Support',
    'Zoom Functionality',
    'Skip to Main Content',
    'Landmark Regions',
    'Tab Order',
    'Focus Indicators',
    'Link Purpose Clear',
    'Button Accessibility',
    'Modal Dialog A11y',
    'Dropdown Menu A11y',
    'Tooltip Accessibility',
    'Table Accessibility',
    'List Structure',
    'Definition Lists',
    'Abbreviation Expansion',
    'Language Declaration',
    'Page Title Accuracy',
    'Iframe Titles',
    'Video Captions',
    'Audio Transcripts',
    'Animation Control',
    'Autoplay Prevention',
    'Time Limits Adjustable',
    'Pause Mechanism',
    'Flashing Content',
    'Motion Reduction',
    'Touch Target Size',
    'Mobile Accessibility',
    'Voice Control Support',
    'High Contrast Mode',
    'Dark Mode Accessibility',
    'Print Stylesheet',
    'PDF Accessibility',
    'Document Structure',
    'Reading Order',
    'Consistent Navigation',
    'Consistent Identification',
    'Predictable Changes',
  ],
};

function generateTests(): Record<string, Test[]> {
  const result: Record<string, Test[]> = {};
  const statuses: Array<'passed' | 'failed' | 'pending'> = ['passed', 'failed', 'pending'];
  
  Object.entries(testCategories).forEach(([category, testNames]) => {
    result[category] = testNames.map((name, index) => {
      const status = statuses[Math.floor(Math.random() * statuses.length)];
      const hours = Math.floor(Math.random() * 48);
      const minutes = Math.floor(Math.random() * 60);
      
      let timeAgo: string;
      if (hours === 0) {
        timeAgo = `${minutes}m ago`;
      } else if (hours < 24) {
        timeAgo = `${hours}h ago`;
      } else {
        const days = Math.floor(hours / 24);
        timeAgo = `${days}d ago`;
      }
      
      return {
        id: `T${category.substring(0, 2)}${String(index + 1).padStart(3, '0')}`,
        name,
        lastRun: timeAgo,
        status,
        duration: Math.floor(Math.random() * 5000) + 100,
      };
    });
  });
  
  return result;
}

export function generateMockTests(): Record<string, Test[]> {
  return generateTests();
}
