name: ci

on:
  push:
  pull_request:
  workflow_dispatch: {}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm ci
      - run: npm run lint --if-present
      - run: npm test --if-present

  docker:
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - name: Set build metadata
        id: build_metadata
        run: |
          echo "BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT
          echo "GIT_COMMIT_COUNT=$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT
      - name: Generate version.json
        run: npm run build:version
      - name: Backup version.json for GitHub Pages
        run: cp version.json /tmp/version.json
      - uses: docker/setup-buildx-action@v3
      - if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.build_metadata.outputs.GIT_COMMIT_COUNT }}
            type=sha,format=short
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}
      - uses: docker/build-push-action@v6
        id: docker_build
        with:
          context: .
          push: ${{ github.event_name == 'push' }}
          #          platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GITHUB_SHA=${{ github.sha }}
            GITHUB_REF=${{ github.ref }}
            GIT_COMMIT_COUNT=${{ steps.build_metadata.outputs.GIT_COMMIT_COUNT }}
            BUILD_DATE=${{ steps.build_metadata.outputs.BUILD_DATE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Publish version info to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          # Ensure we're in the repo root
          cd $GITHUB_WORKSPACE

          # Configure git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Create/checkout gh-pages branch
          git fetch origin gh-pages 2>/dev/null || true
          git checkout gh-pages 2>/dev/null || git checkout --orphan gh-pages

          # Remove all files
          git rm -rf . 2>/dev/null || true

          # Copy version.json from backup (created before Docker build)
          cp /tmp/version.json version.json

          # Commit and push
          git add version.json
          git commit -m "Update version info: Build ${{ steps.build_metadata.outputs.GIT_COMMIT_COUNT }}" || echo "No changes to commit"
          git push origin gh-pages --force
